language: php

cache:
  directories:
  - "$HOME/.composer/cache"

php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  - LARAVEL=5.5 TEST_DB_ENGINE=pgsql
  - LARAVEL=5.5 TEST_DB_ENGINE=mysql
  - LARAVEL=5.5 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.6 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.7 TEST_DB_ENGINE=sqlite
  - LARAVEL=5.8 TEST_DB_ENGINE=sqlite
  - LARAVEL=6.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=6.18 TEST_DB_ENGINE=pgsql
  - LARAVEL=6.18 TEST_DB_ENGINE=mysql
  - LARAVEL=6.18 TEST_DB_ENGINE=sqlite
  - LARAVEL=7.0 TEST_DB_ENGINE=sqlite
  - LARAVEL=7.3 TEST_DB_ENGINE=pgsql
  - LARAVEL=7.3 TEST_DB_ENGINE=mysql
  - LARAVEL=7.3 TEST_DB_ENGINE=sqlite

script:
  - vendor/bin/phpunit --testdox

before_install:
  - MINOR=`echo $LARAVEL | sed 's/[5|6|7]\.\([0-9]\+\)/\1/'`
  - '[[ $LARAVEL =~ ^6\.[0-9]+$ ]] && MAJOR=6 || MAJOR=5'
  - '[[ $LARAVEL =~ ^7\.[0-9]+$ ]] && MAJOR=7 || true'
  - '[ 6 -eq $MAJOR ] && ORCH=4 || ORCH=3'
  - '[ 7 -eq $MAJOR ] && ORCH=5 || true'
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'mysql' = $TEST_DB_ENGINE ] && mysql -e 'DROP DATABASE IF EXISTS order_test;CREATE DATABASE order_test;'" || true
  - sh -c "[ ! -z $TEST_DB_ENGINE ] && [ 'pgsql' = $TEST_DB_ENGINE ] && psql -c 'create database order_test;' -U postgres" || true

install: composer install --no-interaction

services:
  - mysql
  - postgresql

notifications:
  email: false
  slack:
    secure: vNQZI+ZLjfMwhak4wAKAC3BXOhs2Auea35GsPF0fXON0VedHVJ48NKYeMp98cBwe5BXV2TKH5ArZTrxCcXjeOdJXtls2J1WnbawpRbtBUQCu10sudvboVZNGe1IZVGqV1+YpVKAg8t3/Ur6QqDQAmLhlCb61i4e+cSpQcUdo8xRH7fJ4aud8RdFUXDlL9pdct+nJdlkyp8NUffzjU+rSYtWj52ilETUg/8kAQeA9PrYOHaf4kOvg7P0CNNTaQWkMuxM9p7x/jMfrU0/VFLTZJkszzQ0sQRC4EESgvdhSzvvvr3qNQ3dtLU1RVRXhpdNT17OBqwR2jkApKwUkJdtMwwygkVXH51nfgHcEjdfVLVZihc27u25w7OCXCIX9Z47skMAEk/m592qgsJVmlpeZCNKQZux6pqFVF/GBbgiTRYrRNYEpsHz/lBPaJdy+VsUe+xLeYQKFor4jLjCNwfwym7SuXKV5TOVcdGoCUD+l8j8gO1rHbwONdylSK67ZOzynHxg0hgONI1VtUK6o3MDhd7IG5mMnBgVMIbdnEL27KAS68PJswcc4uhc7V1g2B/mTzgwV4Pobk52kw4cXUyqMVk2QdD5ofssI78t+BflnEavV+F9yrEhybXyvYiZpkkv7zdLjU+4IBSALxNu7yy+fp5EK1KTaMcflUHGdQxffZpY=
